export type UsersActionType =
    | 'GETTING_PROFILE_DETAILS'
    | 'GETTING_PROFILE_DETAILS_SUCCESS'
    | 'GETTING_PROFILE_DETAILS_FAILURE';

const GETTING_PROFILE_DETAILS: UsersActionType = 'GETTING_PROFILE_DETAILS';
const GETTING_PROFILE_DETAILS_SUCCESS: UsersActionType =
    'GETTING_PROFILE_DETAILS_SUCCESS';
const GETTING_PROFILE_DETAILS_FAILURE: UsersActionType =
    'GETTING_PROFILE_DETAILS_FAILURE';

export {
    GETTING_PROFILE_DETAILS,
    GETTING_PROFILE_DETAILS_SUCCESS,
    GETTING_PROFILE_DETAILS_FAILURE,
};
